#ifndef DEVOPCUA_DEVOPCUAVERSION_H
#  error include devOpcuaVersion.h, not this header
#endif
#define EPICS_OPCUA_MAJOR_VERSION 0
#define EPICS_OPCUA_MINOR_VERSION 11
#define EPICS_OPCUA_MAINTENANCE_VERSION 2
#define EPICS_OPCUA_DEVELOPMENT_FLAG 0
#define EPICS_OPCUA_GIT_COMMIT "v0.11.2-0-gf9b0c92-dirty"
